// Generated by scripts/world/compile-world.cjs. Do not edit.
setup.worldGraphData = {
  "formatVersion": 1,
  "datasetVersion": "sa-spike-0.1.0",
  "tileKm": 5,
  "sources": [
    {
      "id": "geonames-cities15000-2026-09-20",
      "name": "GeoNames cities15000",
      "url": "https://download.geonames.org/export/dump/cities15000.zip",
      "retrieved": "2026-09-20",
      "license": "CC BY 4.0",
      "attribution": "City names, coordinates and population: GeoNames (https://www.geonames.org/)",
      "status": "ingested",
      "use": "Stable external IDs and coordinates for authored South America waypoints"
    },
    {
      "id": "openstreetmap-rail",
      "name": "OpenStreetMap",
      "url": "https://planet.openstreetmap.org/",
      "license": "ODbL 1.0",
      "attribution": "© OpenStreetMap contributors",
      "status": "planned",
      "use": "Current, disused, abandoned and razed railway geometry and infrastructure"
    },
    {
      "id": "openhistoricalmap-rail",
      "name": "OpenHistoricalMap",
      "url": "https://www.openhistoricalmap.org/",
      "license": "Mostly CC0; inspect license tags on imported features",
      "attribution": "OpenHistoricalMap contributors",
      "status": "planned",
      "use": "Supplementary historical railway alignments"
    },
    {
      "id": "copernicus-dem-glo90",
      "name": "Copernicus DEM GLO-90",
      "url": "https://dataspace.copernicus.eu/explore-data/data-collections/copernicus-contributing-missions/collections-description/COP-DEM",
      "license": "Copernicus WorldDEM-90 free and open licence; prescribed notice required",
      "attribution": "Produced using Copernicus WorldDEM-90 © DLR e.V. 2010-2014 and © Airbus Defence and Space GmbH 2014-2018 provided under COPERNICUS by the European Union and ESA; all rights reserved",
      "status": "planned",
      "use": "Elevation profiles and grades"
    },
    {
      "id": "chelsa-climatologies-2.1",
      "name": "CHELSA climatologies 2.1",
      "url": "https://www.chelsa-climate.org/datasets/chelsa_climatologies",
      "license": "CC0 1.0",
      "attribution": "CHELSA climatologies, Karger et al.",
      "status": "planned",
      "use": "Temperature and relative-humidity normals"
    },
    {
      "id": "hydrorivers-1",
      "name": "HydroRIVERS version 1",
      "url": "https://www.hydrosheds.org/products/hydrorivers",
      "license": "HydroSHEDS licence; attribution required",
      "attribution": "Lehner and Grill (2013), HydroRIVERS / HydroSHEDS",
      "status": "planned",
      "use": "River intersections and crossing importance for missing/generated lines"
    }
  ],
  "regions": [
    {
      "id": "r-n00-w060",
      "file": "regions/r-n00-w060.json",
      "nodeCount": 1,
      "portalCount": 1,
      "linkCount": 1
    },
    {
      "id": "r-n00-w070",
      "file": "regions/r-n00-w070.json",
      "nodeCount": 2,
      "portalCount": 3,
      "linkCount": 4
    },
    {
      "id": "r-n00-w080",
      "file": "regions/r-n00-w080.json",
      "nodeCount": 4,
      "portalCount": 2,
      "linkCount": 7
    },
    {
      "id": "r-n10-w070",
      "file": "regions/r-n10-w070.json",
      "nodeCount": 1,
      "portalCount": 0,
      "linkCount": 0
    },
    {
      "id": "r-n10-w080",
      "file": "regions/r-n10-w080.json",
      "nodeCount": 1,
      "portalCount": 1,
      "linkCount": 1
    },
    {
      "id": "r-s10-w040",
      "file": "regions/r-s10-w040.json",
      "nodeCount": 1,
      "portalCount": 1,
      "linkCount": 1
    },
    {
      "id": "r-s10-w050",
      "file": "regions/r-s10-w050.json",
      "nodeCount": 1,
      "portalCount": 1,
      "linkCount": 1
    },
    {
      "id": "r-s10-w070",
      "file": "regions/r-s10-w070.json",
      "nodeCount": 2,
      "portalCount": 1,
      "linkCount": 2
    },
    {
      "id": "r-s10-w080",
      "file": "regions/r-s10-w080.json",
      "nodeCount": 3,
      "portalCount": 0,
      "linkCount": 2
    },
    {
      "id": "r-s20-w040",
      "file": "regions/r-s20-w040.json",
      "nodeCount": 1,
      "portalCount": 0,
      "linkCount": 0
    },
    {
      "id": "r-s20-w050",
      "file": "regions/r-s20-w050.json",
      "nodeCount": 0,
      "portalCount": 2,
      "linkCount": 1
    },
    {
      "id": "r-s20-w070",
      "file": "regions/r-s20-w070.json",
      "nodeCount": 1,
      "portalCount": 1,
      "linkCount": 1
    },
    {
      "id": "r-s20-w080",
      "file": "regions/r-s20-w080.json",
      "nodeCount": 3,
      "portalCount": 1,
      "linkCount": 3
    },
    {
      "id": "r-s30-w050",
      "file": "regions/r-s30-w050.json",
      "nodeCount": 2,
      "portalCount": 1,
      "linkCount": 2
    },
    {
      "id": "r-s30-w060",
      "file": "regions/r-s30-w060.json",
      "nodeCount": 1,
      "portalCount": 0,
      "linkCount": 0
    },
    {
      "id": "r-s30-w070",
      "file": "regions/r-s30-w070.json",
      "nodeCount": 0,
      "portalCount": 3,
      "linkCount": 2
    },
    {
      "id": "r-s30-w080",
      "file": "regions/r-s30-w080.json",
      "nodeCount": 1,
      "portalCount": 2,
      "linkCount": 2
    },
    {
      "id": "r-s40-w060",
      "file": "regions/r-s40-w060.json",
      "nodeCount": 2,
      "portalCount": 0,
      "linkCount": 1
    },
    {
      "id": "r-s40-w070",
      "file": "regions/r-s40-w070.json",
      "nodeCount": 3,
      "portalCount": 1,
      "linkCount": 2
    },
    {
      "id": "r-s40-w080",
      "file": "regions/r-s40-w080.json",
      "nodeCount": 1,
      "portalCount": 3,
      "linkCount": 2
    },
    {
      "id": "r-s50-w070",
      "file": "regions/r-s50-w070.json",
      "nodeCount": 0,
      "portalCount": 2,
      "linkCount": 1
    },
    {
      "id": "r-s50-w080",
      "file": "regions/r-s50-w080.json",
      "nodeCount": 2,
      "portalCount": 2,
      "linkCount": 2
    },
    {
      "id": "r-s60-w070",
      "file": "regions/r-s60-w070.json",
      "nodeCount": 1,
      "portalCount": 0,
      "linkCount": 0
    },
    {
      "id": "r-s60-w080",
      "file": "regions/r-s60-w080.json",
      "nodeCount": 1,
      "portalCount": 1,
      "linkCount": 2
    }
  ],
  "corridors": [
    {
      "id": "atlantic",
      "label": "Atlantic coast",
      "waypoints": [
        "cl-punta-arenas",
        "ar-rio-gallegos",
        "ar-bahia-blanca",
        "ar-buenos-aires",
        "br-porto-alegre",
        "br-sao-paulo",
        "br-rio-de-janeiro",
        "br-salvador",
        "br-fortaleza",
        "br-belem",
        "gy-georgetown",
        "ve-ciudad-guayana",
        "ve-caracas",
        "co-cartagena",
        "pa-panama-city"
      ],
      "planningLinkIds": [
        "plan:atlantic:01",
        "plan:atlantic:02",
        "plan:atlantic:03",
        "plan:atlantic:04",
        "plan:atlantic:05",
        "plan:atlantic:06",
        "plan:atlantic:07",
        "plan:atlantic:08",
        "plan:atlantic:09",
        "plan:atlantic:10",
        "plan:atlantic:11",
        "plan:atlantic:12",
        "plan:atlantic:13",
        "plan:atlantic:14"
      ]
    },
    {
      "id": "central-amazon",
      "label": "Central and Amazon",
      "waypoints": [
        "cl-punta-arenas",
        "ar-rio-gallegos",
        "ar-bariloche",
        "ar-mendoza",
        "ar-cordoba",
        "py-asuncion",
        "bo-santa-cruz",
        "br-porto-velho",
        "br-manaus",
        "br-boa-vista",
        "ve-ciudad-guayana",
        "co-bogota",
        "co-medellin",
        "pa-panama-city"
      ],
      "planningLinkIds": [
        "plan:central-amazon:01",
        "plan:central-amazon:02",
        "plan:central-amazon:03",
        "plan:central-amazon:04",
        "plan:central-amazon:05",
        "plan:central-amazon:06",
        "plan:central-amazon:07",
        "plan:central-amazon:08",
        "plan:central-amazon:09",
        "plan:central-amazon:10",
        "plan:central-amazon:11",
        "plan:central-amazon:12",
        "plan:central-amazon:13"
      ]
    },
    {
      "id": "pacific",
      "label": "Pacific coast",
      "waypoints": [
        "cl-punta-arenas",
        "cl-puerto-montt",
        "cl-santiago",
        "cl-antofagasta",
        "cl-arica",
        "pe-arequipa",
        "pe-lima",
        "pe-trujillo",
        "ec-guayaquil",
        "ec-quito",
        "co-cali",
        "co-medellin",
        "co-cartagena",
        "pa-panama-city"
      ],
      "planningLinkIds": [
        "plan:pacific:01",
        "plan:pacific:02",
        "plan:pacific:03",
        "plan:pacific:04",
        "plan:pacific:05",
        "plan:pacific:06",
        "plan:pacific:07",
        "plan:pacific:08",
        "plan:pacific:09",
        "plan:pacific:10",
        "plan:pacific:11",
        "plan:pacific:12",
        "plan:pacific:13"
      ]
    }
  ],
  "chunks": {
    "r-n00-w060": {
      "id": "r-n00-w060",
      "nodes": [
        {
          "id": "gy-georgetown",
          "name": "Georgetown",
          "countryCode": "GY",
          "latitude": 6.80448,
          "longitude": -58.15527,
          "population": 235017,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3378644"
        }
      ],
      "portals": [
        {
          "id": "br-belem",
          "name": "Belém",
          "countryCode": "BR",
          "latitude": -1.45583,
          "longitude": -48.50444,
          "population": 1499641,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3405870"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:10",
          "from": "br-belem",
          "to": "gy-georgetown",
          "corridorId": "atlantic",
          "distanceKm": 1410.9,
          "estimatedSlices": 283,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-n00-w070": {
      "id": "r-n00-w070",
      "nodes": [
        {
          "id": "br-boa-vista",
          "name": "Boa Vista",
          "countryCode": "BR",
          "latitude": 2.81972,
          "longitude": -60.67333,
          "population": 419652,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3664980"
        },
        {
          "id": "ve-ciudad-guayana",
          "name": "Ciudad Guayana",
          "countryCode": "VE",
          "latitude": 8.35122,
          "longitude": -62.64102,
          "population": 978202,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3645528"
        }
      ],
      "portals": [
        {
          "id": "co-bogota",
          "name": "Bogotá",
          "countryCode": "CO",
          "latitude": 4.60971,
          "longitude": -74.08175,
          "population": 7674366,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3688689"
        },
        {
          "id": "gy-georgetown",
          "name": "Georgetown",
          "countryCode": "GY",
          "latitude": 6.80448,
          "longitude": -58.15527,
          "population": 235017,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3378644"
        },
        {
          "id": "ve-caracas",
          "name": "Caracas",
          "countryCode": "VE",
          "latitude": 10.48801,
          "longitude": -66.87919,
          "population": 3000000,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3646738"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:11",
          "from": "gy-georgetown",
          "to": "ve-ciudad-guayana",
          "corridorId": "atlantic",
          "distanceKm": 523.5,
          "estimatedSlices": 105,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:atlantic:12",
          "from": "ve-ciudad-guayana",
          "to": "ve-caracas",
          "corridorId": "atlantic",
          "distanceKm": 522.1,
          "estimatedSlices": 105,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:10",
          "from": "br-boa-vista",
          "to": "ve-ciudad-guayana",
          "corridorId": "central-amazon",
          "distanceKm": 652.5,
          "estimatedSlices": 131,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:11",
          "from": "ve-ciudad-guayana",
          "to": "co-bogota",
          "corridorId": "central-amazon",
          "distanceKm": 1330.5,
          "estimatedSlices": 267,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-n00-w080": {
      "id": "r-n00-w080",
      "nodes": [
        {
          "id": "co-bogota",
          "name": "Bogotá",
          "countryCode": "CO",
          "latitude": 4.60971,
          "longitude": -74.08175,
          "population": 7674366,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3688689"
        },
        {
          "id": "co-cali",
          "name": "Cali",
          "countryCode": "CO",
          "latitude": 3.43054,
          "longitude": -76.5199,
          "population": 2392877,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3687925"
        },
        {
          "id": "co-medellin",
          "name": "Medellín",
          "countryCode": "CO",
          "latitude": 6.245,
          "longitude": -75.57151,
          "population": 1999979,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3674962"
        },
        {
          "id": "pa-panama-city",
          "name": "Panama City",
          "countryCode": "PA",
          "latitude": 8.9936,
          "longitude": -79.51973,
          "population": 408168,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3703443"
        }
      ],
      "portals": [
        {
          "id": "co-cartagena",
          "name": "Cartagena",
          "countryCode": "CO",
          "latitude": 10.39817,
          "longitude": -75.49328,
          "population": 914552,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3687238"
        },
        {
          "id": "ec-quito",
          "name": "Quito",
          "countryCode": "EC",
          "latitude": -0.22985,
          "longitude": -78.52495,
          "population": 2781641,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3652462"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:14",
          "from": "co-cartagena",
          "to": "pa-panama-city",
          "corridorId": "atlantic",
          "distanceKm": 468.1,
          "estimatedSlices": 94,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:12",
          "from": "co-bogota",
          "to": "co-medellin",
          "corridorId": "central-amazon",
          "distanceKm": 245.5,
          "estimatedSlices": 50,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:13",
          "from": "co-medellin",
          "to": "pa-panama-city",
          "corridorId": "central-amazon",
          "distanceKm": 531.7,
          "estimatedSlices": 107,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:10",
          "from": "ec-quito",
          "to": "co-cali",
          "corridorId": "pacific",
          "distanceKm": 464,
          "estimatedSlices": 93,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:11",
          "from": "co-cali",
          "to": "co-medellin",
          "corridorId": "pacific",
          "distanceKm": 330.1,
          "estimatedSlices": 67,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:12",
          "from": "co-medellin",
          "to": "co-cartagena",
          "corridorId": "pacific",
          "distanceKm": 461.9,
          "estimatedSlices": 93,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:13",
          "from": "co-cartagena",
          "to": "pa-panama-city",
          "corridorId": "pacific",
          "distanceKm": 468.1,
          "estimatedSlices": 94,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-n10-w070": {
      "id": "r-n10-w070",
      "nodes": [
        {
          "id": "ve-caracas",
          "name": "Caracas",
          "countryCode": "VE",
          "latitude": 10.48801,
          "longitude": -66.87919,
          "population": 3000000,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3646738"
        }
      ],
      "portals": [],
      "links": []
    },
    "r-n10-w080": {
      "id": "r-n10-w080",
      "nodes": [
        {
          "id": "co-cartagena",
          "name": "Cartagena",
          "countryCode": "CO",
          "latitude": 10.39817,
          "longitude": -75.49328,
          "population": 914552,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3687238"
        }
      ],
      "portals": [
        {
          "id": "ve-caracas",
          "name": "Caracas",
          "countryCode": "VE",
          "latitude": 10.48801,
          "longitude": -66.87919,
          "population": 3000000,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3646738"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:13",
          "from": "ve-caracas",
          "to": "co-cartagena",
          "corridorId": "atlantic",
          "distanceKm": 942,
          "estimatedSlices": 189,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s10-w040": {
      "id": "r-s10-w040",
      "nodes": [
        {
          "id": "br-fortaleza",
          "name": "Fortaleza",
          "countryCode": "BR",
          "latitude": -3.71722,
          "longitude": -38.54306,
          "population": 2400000,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3399415"
        }
      ],
      "portals": [
        {
          "id": "br-salvador",
          "name": "Salvador",
          "countryCode": "BR",
          "latitude": -12.97563,
          "longitude": -38.49096,
          "population": 2711840,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3450554"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:08",
          "from": "br-salvador",
          "to": "br-fortaleza",
          "corridorId": "atlantic",
          "distanceKm": 1029.5,
          "estimatedSlices": 206,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s10-w050": {
      "id": "r-s10-w050",
      "nodes": [
        {
          "id": "br-belem",
          "name": "Belém",
          "countryCode": "BR",
          "latitude": -1.45583,
          "longitude": -48.50444,
          "population": 1499641,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3405870"
        }
      ],
      "portals": [
        {
          "id": "br-fortaleza",
          "name": "Fortaleza",
          "countryCode": "BR",
          "latitude": -3.71722,
          "longitude": -38.54306,
          "population": 2400000,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3399415"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:09",
          "from": "br-fortaleza",
          "to": "br-belem",
          "corridorId": "atlantic",
          "distanceKm": 1134.7,
          "estimatedSlices": 227,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s10-w070": {
      "id": "r-s10-w070",
      "nodes": [
        {
          "id": "br-manaus",
          "name": "Manaus",
          "countryCode": "BR",
          "latitude": -3.10194,
          "longitude": -60.025,
          "population": 2219580,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3663517"
        },
        {
          "id": "br-porto-velho",
          "name": "Porto Velho",
          "countryCode": "BR",
          "latitude": -8.76194,
          "longitude": -63.90389,
          "population": 548952,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3662762"
        }
      ],
      "portals": [
        {
          "id": "br-boa-vista",
          "name": "Boa Vista",
          "countryCode": "BR",
          "latitude": 2.81972,
          "longitude": -60.67333,
          "population": 419652,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3664980"
        }
      ],
      "links": [
        {
          "id": "plan:central-amazon:08",
          "from": "br-porto-velho",
          "to": "br-manaus",
          "corridorId": "central-amazon",
          "distanceKm": 761.6,
          "estimatedSlices": 153,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:09",
          "from": "br-manaus",
          "to": "br-boa-vista",
          "corridorId": "central-amazon",
          "distanceKm": 662.4,
          "estimatedSlices": 133,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s10-w080": {
      "id": "r-s10-w080",
      "nodes": [
        {
          "id": "ec-guayaquil",
          "name": "Guayaquil",
          "countryCode": "EC",
          "latitude": -2.19616,
          "longitude": -79.88621,
          "population": 2723665,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3657509"
        },
        {
          "id": "ec-quito",
          "name": "Quito",
          "countryCode": "EC",
          "latitude": -0.22985,
          "longitude": -78.52495,
          "population": 2781641,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3652462"
        },
        {
          "id": "pe-trujillo",
          "name": "Trujillo",
          "countryCode": "PE",
          "latitude": -8.11599,
          "longitude": -79.02998,
          "population": 1067700,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3691175"
        }
      ],
      "portals": [],
      "links": [
        {
          "id": "plan:pacific:08",
          "from": "pe-trujillo",
          "to": "ec-guayaquil",
          "corridorId": "pacific",
          "distanceKm": 665,
          "estimatedSlices": 133,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:09",
          "from": "ec-guayaquil",
          "to": "ec-quito",
          "corridorId": "pacific",
          "distanceKm": 265.9,
          "estimatedSlices": 54,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s20-w040": {
      "id": "r-s20-w040",
      "nodes": [
        {
          "id": "br-salvador",
          "name": "Salvador",
          "countryCode": "BR",
          "latitude": -12.97563,
          "longitude": -38.49096,
          "population": 2711840,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3450554"
        }
      ],
      "portals": [],
      "links": []
    },
    "r-s20-w050": {
      "id": "r-s20-w050",
      "nodes": [],
      "portals": [
        {
          "id": "br-rio-de-janeiro",
          "name": "Rio de Janeiro",
          "countryCode": "BR",
          "latitude": -22.90642,
          "longitude": -43.18223,
          "population": 6747815,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3451190"
        },
        {
          "id": "br-salvador",
          "name": "Salvador",
          "countryCode": "BR",
          "latitude": -12.97563,
          "longitude": -38.49096,
          "population": 2711840,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3450554"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:07",
          "from": "br-rio-de-janeiro",
          "to": "br-salvador",
          "corridorId": "atlantic",
          "distanceKm": 1210.3,
          "estimatedSlices": 243,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s20-w070": {
      "id": "r-s20-w070",
      "nodes": [
        {
          "id": "bo-santa-cruz",
          "name": "Santa Cruz de la Sierra",
          "countryCode": "BO",
          "latitude": -17.78629,
          "longitude": -63.18117,
          "population": 1831434,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3904906"
        }
      ],
      "portals": [
        {
          "id": "br-porto-velho",
          "name": "Porto Velho",
          "countryCode": "BR",
          "latitude": -8.76194,
          "longitude": -63.90389,
          "population": 548952,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3662762"
        }
      ],
      "links": [
        {
          "id": "plan:central-amazon:07",
          "from": "bo-santa-cruz",
          "to": "br-porto-velho",
          "corridorId": "central-amazon",
          "distanceKm": 1006.5,
          "estimatedSlices": 202,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s20-w080": {
      "id": "r-s20-w080",
      "nodes": [
        {
          "id": "cl-arica",
          "name": "Arica",
          "countryCode": "CL",
          "latitude": -18.47552,
          "longitude": -70.30058,
          "population": 241653,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3899361"
        },
        {
          "id": "pe-arequipa",
          "name": "Arequipa",
          "countryCode": "PE",
          "latitude": -16.39899,
          "longitude": -71.53747,
          "population": 1195700,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3947322"
        },
        {
          "id": "pe-lima",
          "name": "Lima",
          "countryCode": "PE",
          "latitude": -12.04318,
          "longitude": -77.02824,
          "population": 7737002,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3936456"
        }
      ],
      "portals": [
        {
          "id": "pe-trujillo",
          "name": "Trujillo",
          "countryCode": "PE",
          "latitude": -8.11599,
          "longitude": -79.02998,
          "population": 1067700,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3691175"
        }
      ],
      "links": [
        {
          "id": "plan:pacific:05",
          "from": "cl-arica",
          "to": "pe-arequipa",
          "corridorId": "pacific",
          "distanceKm": 265.6,
          "estimatedSlices": 54,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:06",
          "from": "pe-arequipa",
          "to": "pe-lima",
          "corridorId": "pacific",
          "distanceKm": 764.6,
          "estimatedSlices": 153,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:07",
          "from": "pe-lima",
          "to": "pe-trujillo",
          "corridorId": "pacific",
          "distanceKm": 488.6,
          "estimatedSlices": 98,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s30-w050": {
      "id": "r-s30-w050",
      "nodes": [
        {
          "id": "br-rio-de-janeiro",
          "name": "Rio de Janeiro",
          "countryCode": "BR",
          "latitude": -22.90642,
          "longitude": -43.18223,
          "population": 6747815,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3451190"
        },
        {
          "id": "br-sao-paulo",
          "name": "São Paulo",
          "countryCode": "BR",
          "latitude": -23.5475,
          "longitude": -46.63611,
          "population": 12400232,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3448439"
        }
      ],
      "portals": [
        {
          "id": "br-porto-alegre",
          "name": "Porto Alegre",
          "countryCode": "BR",
          "latitude": -30.03283,
          "longitude": -51.23019,
          "population": 1488252,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3452925"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:05",
          "from": "br-porto-alegre",
          "to": "br-sao-paulo",
          "corridorId": "atlantic",
          "distanceKm": 853,
          "estimatedSlices": 171,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:atlantic:06",
          "from": "br-sao-paulo",
          "to": "br-rio-de-janeiro",
          "corridorId": "atlantic",
          "distanceKm": 360,
          "estimatedSlices": 72,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s30-w060": {
      "id": "r-s30-w060",
      "nodes": [
        {
          "id": "py-asuncion",
          "name": "Asunción",
          "countryCode": "PY",
          "latitude": -25.28646,
          "longitude": -57.647,
          "population": 1482200,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3439389"
        }
      ],
      "portals": [],
      "links": []
    },
    "r-s30-w070": {
      "id": "r-s30-w070",
      "nodes": [],
      "portals": [
        {
          "id": "ar-cordoba",
          "name": "Córdoba",
          "countryCode": "AR",
          "latitude": -31.40648,
          "longitude": -64.18853,
          "population": 2106734,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3860259"
        },
        {
          "id": "bo-santa-cruz",
          "name": "Santa Cruz de la Sierra",
          "countryCode": "BO",
          "latitude": -17.78629,
          "longitude": -63.18117,
          "population": 1831434,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3904906"
        },
        {
          "id": "py-asuncion",
          "name": "Asunción",
          "countryCode": "PY",
          "latitude": -25.28646,
          "longitude": -57.647,
          "population": 1482200,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3439389"
        }
      ],
      "links": [
        {
          "id": "plan:central-amazon:05",
          "from": "ar-cordoba",
          "to": "py-asuncion",
          "corridorId": "central-amazon",
          "distanceKm": 933.9,
          "estimatedSlices": 187,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:06",
          "from": "py-asuncion",
          "to": "bo-santa-cruz",
          "corridorId": "central-amazon",
          "distanceKm": 1011.2,
          "estimatedSlices": 203,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s30-w080": {
      "id": "r-s30-w080",
      "nodes": [
        {
          "id": "cl-antofagasta",
          "name": "Antofagasta",
          "countryCode": "CL",
          "latitude": -23.65094,
          "longitude": -70.39752,
          "population": 401096,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3899539"
        }
      ],
      "portals": [
        {
          "id": "cl-arica",
          "name": "Arica",
          "countryCode": "CL",
          "latitude": -18.47552,
          "longitude": -70.30058,
          "population": 241653,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3899361"
        },
        {
          "id": "cl-santiago",
          "name": "Santiago",
          "countryCode": "CL",
          "latitude": -33.45694,
          "longitude": -70.64827,
          "population": 4837295,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3871336"
        }
      ],
      "links": [
        {
          "id": "plan:pacific:03",
          "from": "cl-santiago",
          "to": "cl-antofagasta",
          "corridorId": "pacific",
          "distanceKm": 1090.7,
          "estimatedSlices": 219,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:04",
          "from": "cl-antofagasta",
          "to": "cl-arica",
          "corridorId": "pacific",
          "distanceKm": 575.6,
          "estimatedSlices": 116,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s40-w060": {
      "id": "r-s40-w060",
      "nodes": [
        {
          "id": "ar-buenos-aires",
          "name": "Buenos Aires",
          "countryCode": "AR",
          "latitude": -34.61315,
          "longitude": -58.37723,
          "population": 2891082,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3435910"
        },
        {
          "id": "br-porto-alegre",
          "name": "Porto Alegre",
          "countryCode": "BR",
          "latitude": -30.03283,
          "longitude": -51.23019,
          "population": 1488252,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3452925"
        }
      ],
      "portals": [],
      "links": [
        {
          "id": "plan:atlantic:04",
          "from": "ar-buenos-aires",
          "to": "br-porto-alegre",
          "corridorId": "atlantic",
          "distanceKm": 842.4,
          "estimatedSlices": 169,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s40-w070": {
      "id": "r-s40-w070",
      "nodes": [
        {
          "id": "ar-bahia-blanca",
          "name": "Bahía Blanca",
          "countryCode": "AR",
          "latitude": -38.7176,
          "longitude": -62.26545,
          "population": 299101,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3865086"
        },
        {
          "id": "ar-cordoba",
          "name": "Córdoba",
          "countryCode": "AR",
          "latitude": -31.40648,
          "longitude": -64.18853,
          "population": 2106734,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3860259"
        },
        {
          "id": "ar-mendoza",
          "name": "Mendoza",
          "countryCode": "AR",
          "latitude": -32.88946,
          "longitude": -68.84582,
          "population": 114893,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3844421"
        }
      ],
      "portals": [
        {
          "id": "ar-buenos-aires",
          "name": "Buenos Aires",
          "countryCode": "AR",
          "latitude": -34.61315,
          "longitude": -58.37723,
          "population": 2891082,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3435910"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:03",
          "from": "ar-bahia-blanca",
          "to": "ar-buenos-aires",
          "corridorId": "atlantic",
          "distanceKm": 573.1,
          "estimatedSlices": 115,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:04",
          "from": "ar-mendoza",
          "to": "ar-cordoba",
          "corridorId": "central-amazon",
          "distanceKm": 468.4,
          "estimatedSlices": 94,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s40-w080": {
      "id": "r-s40-w080",
      "nodes": [
        {
          "id": "cl-santiago",
          "name": "Santiago",
          "countryCode": "CL",
          "latitude": -33.45694,
          "longitude": -70.64827,
          "population": 4837295,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3871336"
        }
      ],
      "portals": [
        {
          "id": "ar-bariloche",
          "name": "San Carlos de Bariloche",
          "countryCode": "AR",
          "latitude": -41.14557,
          "longitude": -71.30822,
          "population": 95394,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "7647007"
        },
        {
          "id": "ar-mendoza",
          "name": "Mendoza",
          "countryCode": "AR",
          "latitude": -32.88946,
          "longitude": -68.84582,
          "population": 114893,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3844421"
        },
        {
          "id": "cl-puerto-montt",
          "name": "Puerto Montt",
          "countryCode": "CL",
          "latitude": -41.4693,
          "longitude": -72.94237,
          "population": 245902,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3874960"
        }
      ],
      "links": [
        {
          "id": "plan:central-amazon:03",
          "from": "ar-bariloche",
          "to": "ar-mendoza",
          "corridorId": "central-amazon",
          "distanceKm": 943.6,
          "estimatedSlices": 189,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:02",
          "from": "cl-puerto-montt",
          "to": "cl-santiago",
          "corridorId": "pacific",
          "distanceKm": 913.6,
          "estimatedSlices": 183,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s50-w070": {
      "id": "r-s50-w070",
      "nodes": [],
      "portals": [
        {
          "id": "ar-bahia-blanca",
          "name": "Bahía Blanca",
          "countryCode": "AR",
          "latitude": -38.7176,
          "longitude": -62.26545,
          "population": 299101,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3865086"
        },
        {
          "id": "ar-rio-gallegos",
          "name": "Río Gallegos",
          "countryCode": "AR",
          "latitude": -51.6253,
          "longitude": -69.25229,
          "population": 95796,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3838859"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:02",
          "from": "ar-rio-gallegos",
          "to": "ar-bahia-blanca",
          "corridorId": "atlantic",
          "distanceKm": 1534.5,
          "estimatedSlices": 307,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s50-w080": {
      "id": "r-s50-w080",
      "nodes": [
        {
          "id": "ar-bariloche",
          "name": "San Carlos de Bariloche",
          "countryCode": "AR",
          "latitude": -41.14557,
          "longitude": -71.30822,
          "population": 95394,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "7647007"
        },
        {
          "id": "cl-puerto-montt",
          "name": "Puerto Montt",
          "countryCode": "CL",
          "latitude": -41.4693,
          "longitude": -72.94237,
          "population": 245902,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3874960"
        }
      ],
      "portals": [
        {
          "id": "ar-rio-gallegos",
          "name": "Río Gallegos",
          "countryCode": "AR",
          "latitude": -51.6253,
          "longitude": -69.25229,
          "population": 95796,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3838859"
        },
        {
          "id": "cl-punta-arenas",
          "name": "Punta Arenas",
          "countryCode": "CL",
          "latitude": -53.16282,
          "longitude": -70.90922,
          "population": 117430,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3874787"
        }
      ],
      "links": [
        {
          "id": "plan:central-amazon:02",
          "from": "ar-rio-gallegos",
          "to": "ar-bariloche",
          "corridorId": "central-amazon",
          "distanceKm": 1175.8,
          "estimatedSlices": 236,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:pacific:01",
          "from": "cl-punta-arenas",
          "to": "cl-puerto-montt",
          "corridorId": "pacific",
          "distanceKm": 1309.1,
          "estimatedSlices": 262,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    },
    "r-s60-w070": {
      "id": "r-s60-w070",
      "nodes": [
        {
          "id": "ar-rio-gallegos",
          "name": "Río Gallegos",
          "countryCode": "AR",
          "latitude": -51.6253,
          "longitude": -69.25229,
          "population": 95796,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3838859"
        }
      ],
      "portals": [],
      "links": []
    },
    "r-s60-w080": {
      "id": "r-s60-w080",
      "nodes": [
        {
          "id": "cl-punta-arenas",
          "name": "Punta Arenas",
          "countryCode": "CL",
          "latitude": -53.16282,
          "longitude": -70.90922,
          "population": 117430,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3874787"
        }
      ],
      "portals": [
        {
          "id": "ar-rio-gallegos",
          "name": "Río Gallegos",
          "countryCode": "AR",
          "latitude": -51.6253,
          "longitude": -69.25229,
          "population": 95796,
          "sourceId": "geonames-cities15000-2026-09-20",
          "sourceFeatureId": "3838859"
        }
      ],
      "links": [
        {
          "id": "plan:atlantic:01",
          "from": "cl-punta-arenas",
          "to": "ar-rio-gallegos",
          "corridorId": "atlantic",
          "distanceKm": 204.6,
          "estimatedSlices": 41,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        },
        {
          "id": "plan:central-amazon:01",
          "from": "cl-punta-arenas",
          "to": "ar-rio-gallegos",
          "corridorId": "central-amazon",
          "distanceKm": 204.6,
          "estimatedSlices": 41,
          "status": "planning",
          "navigable": false,
          "reviewRequired": true,
          "geometrySource": "authored-waypoint-chord"
        }
      ]
    }
  }
};
